name: performa

services:
  db:
    image: mariadb:10.6.4-focal
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root_performa
      MARIADB_DATABASE: wordpress_performa
      MARIADB_USER: wordpress_performa
      MARIADB_PASSWORD: wordpress_performa

  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_performa
      WORDPRESS_DB_PASSWORD: wordpress_performa
      WORDPRESS_DB_NAME: wordpress_performa
    volumes:
      - ../wp-content:/var/www/html/wp-content

volumes:
  db_data: